# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2BVDbv1pCoTMOFd--ugjTTB_6tu8STH

# **#Part 1 – Data Collection and Preprocessing**
"""

!pip -q install statsmodels seaborn

"""1.1 *Importing* Required Libraries"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plt.style.use("ggplot")

print("Libraries Imported Successfully")

"""**1.2 **Loading** the German Electricity Demand *Dataset***"""

file_path = "/content/drive/MyDrive/MACHINE LEARNING PROJECT/time_series_60min_singleindex.csv"

"""1.3 Data Cleaning"""

import pandas as pd

df = pd.read_csv(
    file_path,
    parse_dates=["utc_timestamp"]
)

print("Dataset Shape:", df.shape)

df.head()

"""1.4 Resampling the Time Series"""

df.describe()

df = df[[
    "utc_timestamp",
    "DE_load_actual_entsoe_transparency"
]]

df.head()

df.columns = [
    "timestamp",
    "load"
]

df.head()

df = df.dropna()

print(df.shape)

df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.set_index("timestamp")

df = df.sort_index()

print(df.index)

df = df.loc["2015-01-01":"2020-10-31"]

print(df.shape)

daily = df.resample("D").mean()

weekly = df.resample("W").mean()

print(daily.head())

print(weekly.head())

df.describe()

daily = df.resample("D").mean()

daily.head()

weekly = df.resample("W").mean()

weekly.head()



"""1.5 Exploratory Data Analysis (EDA)"""

plt.figure(figsize=(18,5))

plt.plot(df.index, df["load"])

plt.title("German Electricity Demand (Hourly)")

plt.xlabel("Year")

plt.ylabel("Load (MW)")

plt.show()

"""**Daily Average Electricity Demand**"""

plt.figure(figsize=(18,5))

plt.plot(
    daily.index,
    daily["load"],
    color="green"
)

plt.title("Daily Average Electricity Demand")

plt.xlabel("Year")

plt.ylabel("Load")

plt.show()

"""**Weekly Average Electricity Demand**"""

plt.figure(figsize=(18,5))

plt.plot(
    weekly.index,
    weekly["load"],
    color="red"
)

plt.title("Weekly Average Electricity Demand")

plt.xlabel("Year")

plt.ylabel("Load")

plt.show()

"""**Distribution of Weekly Electricity Demand**"""

plt.figure(figsize=(10,5))

sns.histplot(
    weekly["load"],
    bins=30,
    kde=True
)

plt.title("Distribution of Weekly Electricity Demand")

plt.show()

"""**Weekly Electricity Demand Boxplot**"""

plt.figure(figsize=(7,5))

sns.boxplot(
    y=weekly["load"]
)

plt.title("Weekly Electricity Demand")

plt.show()

"""**Seasonal Decomposition**"""

decomposition = seasonal_decompose(
    weekly["load"],
    model="additive",
    period=52
)

fig = decomposition.plot()

fig.set_size_inches(16,10)

plt.show()

"""**1.6 Rolling Statistics**"""

rolling_mean = weekly["load"].rolling(window=12).mean()

rolling_std = weekly["load"].rolling(window=12).std()

plt.figure(figsize=(18,6))

plt.plot(
    weekly.index,
    weekly["load"],
    label="Original"
)

plt.plot(
    weekly.index,
    rolling_mean,
    label="Rolling Mean"
)

plt.plot(
    weekly.index,
    rolling_std,
    label="Rolling Std"
)

plt.legend()

plt.show()

"""**1.7 Stationarity Tests**"""

result = adfuller(
    weekly["load"]
)

print("ADF Statistic :", result[0])

print("p-value :", result[1])

print()

print("Critical Values")

for key,value in result[4].items():
    print(key,":",value)

"""**KPSS Test**"""

result = kpss(
    weekly["load"],
    regression="c",
    nlags="auto"
)

print("KPSS Statistic :", result[0])

print("p-value :", result[1])

print()

print("Critical Values")

for key,value in result[3].items():
    print(key,":",value)

plot_acf(
    weekly["load"],
    lags=60
)

plt.show()

plt.figure(figsize=(4,4))

sns.heatmap(
    weekly.corr(),
    annot=True,
    cmap="Blues"
)

plt.show()

print("Hourly observations :", len(df))

print("Daily observations :", len(daily))

print("Weekly observations :", len(weekly))

print()

print("Start Date :", weekly.index.min())

print("End Date :", weekly.index.max())

print()

print("Average Weekly Load :", round(weekly["load"].mean(),2))

print("Maximum Weekly Load :", round(weekly["load"].max(),2))

print("Minimum Weekly Load :", round(weekly["load"].min(),2))



"""#Part 2 – Benchmark Forecast Models"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import numpy as np
import pandas as pd

"""**2.1 Train-Test Split**"""

TEST_WEEKS = 104

train = weekly.iloc[:-TEST_WEEKS]

test = weekly.iloc[-TEST_WEEKS:]

print("Training Weeks :", len(train))
print("Testing Weeks :", len(test))

h = len(test)

print(h)

"""**2.2 Mean Forecast Model**"""

mean_value = train["load"].mean()

mean_forecast = pd.Series(
    mean_value,
    index=test.index
)

mean_forecast.head()

"""**2.3 Naïve Forecast Model**"""

last_value = train["load"].iloc[-1]

naive_forecast = pd.Series(
    last_value,
    index=test.index
)

naive_forecast.head()

"""**2.4 Seasonal Naïve Forecast Model**"""

season_length = 52

seasonal_values = train["load"].iloc[-season_length:].values

forecast_values = np.tile(
    seasonal_values,
    int(np.ceil(h/season_length))
)[:h]

seasonal_naive = pd.Series(
    forecast_values,
    index=test.index
)

seasonal_naive.head()

"""**2.5 Drift Forecast Model**"""

first = train["load"].iloc[0]

last = train["load"].iloc[-1]

n = len(train)

drift = []

for i in range(1, h+1):

    forecast = last + i*((last-first)/(n-1))

    drift.append(forecast)

drift_forecast = pd.Series(
    drift,
    index=test.index
)

drift_forecast.head()

"""**2.6 Benchmark Model Comparison**"""

plt.figure(figsize=(18,6))

plt.plot(
    train.index,
    train["load"],
    label="Training"
)

plt.plot(
    test.index,
    test["load"],
    label="Actual",
    linewidth=3
)

plt.plot(
    mean_forecast.index,
    mean_forecast,
    label="Mean"
)

plt.plot(
    naive_forecast.index,
    naive_forecast,
    label="Naive"
)

plt.plot(
    seasonal_naive.index,
    seasonal_naive,
    label="Seasonal Naive"
)

plt.plot(
    drift_forecast.index,
    drift_forecast,
    label="Drift"
)

plt.legend()

plt.title("Benchmark Forecast Models")

plt.show()

def evaluate(actual, predicted):

    mae = mean_absolute_error(actual, predicted)

    rmse = np.sqrt(
        mean_squared_error(
            actual,
            predicted
        )
    )

    mape = np.mean(
        np.abs((actual-predicted)/actual)
    )*100

    return mae, rmse, mape

mean_mae, mean_rmse, mean_mape = evaluate(
    test["load"],
    mean_forecast
)

naive_mae, naive_rmse, naive_mape = evaluate(
    test["load"],
    naive_forecast
)

seasonal_mae, seasonal_rmse, seasonal_mape = evaluate(
    test["load"],
    seasonal_naive
)

drift_mae, drift_rmse, drift_mape = evaluate(
    test["load"],
    drift_forecast
)

results = pd.DataFrame({

    "Model":[
        "Mean",
        "Naive",
        "Seasonal Naive",
        "Drift"
    ],

    "MAE":[
        mean_mae,
        naive_mae,
        seasonal_mae,
        drift_mae
    ],

    "RMSE":[
        mean_rmse,
        naive_rmse,
        seasonal_rmse,
        drift_rmse
    ],

    "MAPE":[
        mean_mape,
        naive_mape,
        seasonal_mape,
        drift_mape
    ]

})

results = results.sort_values("RMSE")

results

benchmark_metrics = pd.DataFrame({

    "Model":[
        "Mean",
        "Naïve",
        "Seasonal Naïve",
        "Drift"
    ],

    "MAE":[
        mean_mae,
        naive_mae,
        seasonal_mae,
        drift_mae
    ],

    "RMSE":[
        mean_rmse,
        naive_rmse,
        seasonal_rmse,
        drift_rmse
    ],

    "MAPE":[
        mean_mape,
        naive_mape,
        seasonal_mape,
        drift_mape
    ],

    "R2":[
        np.nan,
        np.nan,
        np.nan,
        np.nan
    ]

})

benchmark_metrics

plt.figure(figsize=(8,5))

plt.bar(
    results["Model"],
    results["RMSE"]
)

plt.ylabel("RMSE")

plt.title("Benchmark Model Comparison")

plt.xticks(rotation=20)

plt.show()

results.to_csv(
    "benchmark_model_results.csv",
    index=False
)

print(results)

forecast_df = pd.DataFrame({

    "Actual":test["load"],

    "Mean":mean_forecast,

    "Naive":naive_forecast,

    "Seasonal_Naive":seasonal_naive,

    "Drift":drift_forecast

})

forecast_df.to_csv(
    "benchmark_forecasts.csv"
)

forecast_df.head()



"""#Part 3A – SARIMA Grid Search using AIC"""

import warnings
warnings.filterwarnings("ignore")

import itertools
import numpy as np
import pandas as pd

from statsmodels.tsa.statespace.sarimax import SARIMAX
from tqdm.notebook import tqdm

print("Training observations:", len(train))
print("Testing observations:", len(test))

print(train.head())

p = [0,1,2,3]
d = [0,1]
q = [0,1,2,3]

P = [0,1]
D = [0,1]
Q = [0,1]

seasonal_period = 52

pdq = list(itertools.product(p,d,q))
seasonal_pdq = list(itertools.product(P,D,Q))

print("Models to evaluate:",
      len(pdq)*len(seasonal_pdq))

results = []

best_aic = np.inf

best_order = None

best_seasonal = None

best_model = None

failed = 0

for order in tqdm(pdq):

    for seasonal in seasonal_pdq:

        seasonal_order = (
            seasonal[0],
            seasonal[1],
            seasonal[2],
            seasonal_period
        )

        try:

            model = SARIMAX(

                train["load"],

                order=order,

                seasonal_order=seasonal_order,

                enforce_stationarity=False,

                enforce_invertibility=False

            )

            fit = model.fit(
                disp=False,
                maxiter=50
            )

            aic = fit.aic

            bic = fit.bic

            results.append([

                order,

                seasonal_order,

                aic,

                bic

            ])

            if aic < best_aic:

                best_aic = aic

                best_order = order

                best_seasonal = seasonal_order

                best_model = fit

        except Exception:

            failed += 1

            continue

print("Failed Models :", failed)

print("Successful Models :", len(results))

aic_results = pd.DataFrame(

    results,

    columns=[

        "Order",

        "Seasonal_Order",

        "AIC",

        "BIC"

    ]

)

aic_results = aic_results.sort_values(
    by="AIC"
)

aic_results.head(20)

if best_model is None:

    print("No SARIMA model converged.")

else:

    print("Best Order :", best_order)

    print("Best Seasonal :", best_seasonal)

    print("Best AIC :", round(best_aic,2))

aic_results.to_csv(
    "sarima_grid_search_results.csv",
    index=False
)

print("Saved Successfully")

aic_results.head(10)

from statsmodels.tsa.statespace.sarimax import SARIMAX

model = SARIMAX(
    train["load"],
    order=(1,1,1),
    seasonal_order=(1,1,1,52),
    enforce_stationarity=True,
    enforce_invertibility=True
)

best_model = model.fit(disp=False)

print(best_model.summary())



"""#PART 3B – SARIMA Forecasting and Model *Diagnostics*

Display Best Model
"""

print("="*60)
print("BEST SARIMA MODEL")
print("="*60)

print("Best Order:", best_order)
print("Best Seasonal Order:", best_seasonal)
print("Best AIC:", round(best_aic,2))

forecast = best_model.get_forecast(
    steps=len(test)
)

forecast_mean = forecast.predicted_mean

forecast_ci = forecast.conf_int()

forecast_mean.head()

forecast_ci.columns = [
    "Lower CI",
    "Upper CI"
]

forecast_ci.head()

forecast_df = pd.DataFrame({

    "Actual":test["load"],

    "Forecast":forecast_mean,

    "Lower CI":forecast_ci["Lower CI"],

    "Upper CI":forecast_ci["Upper CI"]

})

forecast_df.head()

plt.figure(figsize=(18,6))

plt.plot(
    train.index,
    train["load"],
    label="Training Data",
    color="blue"
)

plt.plot(
    test.index,
    test["load"],
    label="Actual",
    color="black",
    linewidth=2
)

plt.plot(
    forecast_mean.index,
    forecast_mean,
    label="SARIMA Forecast",
    color="red",
    linewidth=2
)

plt.fill_between(
    forecast_ci.index,
    forecast_ci["Lower CI"],
    forecast_ci["Upper CI"],
    color="pink",
    alpha=0.30,
    label="95% Confidence Interval"
)

plt.title("SARIMA Forecast")

plt.xlabel("Date")

plt.ylabel("Electricity Load")

plt.legend()

plt.grid(True)

plt.show()



"""Evaluation Metrics"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

mae = mean_absolute_error(
    test["load"],
    forecast_mean
)

rmse = np.sqrt(
    mean_squared_error(
        test["load"],
        forecast_mean
    )
)

mape = np.mean(
    np.abs(
        (test["load"]-forecast_mean)
        /
        test["load"]
    )
)*100

r2 = r2_score(
    test["load"],
    forecast_mean
)

print("MAE :",round(mae,2))
print("RMSE :",round(rmse,2))
print("MAPE :",round(mape,2))
print("R² :",round(r2,4))

sarima_metrics = pd.DataFrame({

    "Model":["SARIMA"],

    "MAE":[mae],

    "RMSE":[rmse],

    "MAPE":[mape],

    "R2":[r2]

})

sarima_metrics

residuals = best_model.resid

residuals.describe()

plt.figure(figsize=(18,5))

plt.plot(
    residuals,
    color="purple"
)

plt.axhline(
    0,
    linestyle="--",
    color="black"
)

plt.title("Residual Plot")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(
    residuals,
    kde=True,
    bins=35
)

plt.title("Residual Distribution")

plt.show()

from statsmodels.graphics.gofplots import qqplot

qqplot(
    residuals,
    line="45",
    fit=True
)

plt.title("QQ Plot")

plt.show()

from statsmodels.graphics.tsaplots import plot_acf

plot_acf(
    residuals,
    lags=40
)

plt.show()

from statsmodels.stats.diagnostic import acorr_ljungbox

lb = acorr_ljungbox(
    residuals,
    lags=[10,20,30],
    return_df=True
)

lb

plt.figure(figsize=(18,6))

plt.plot(
    forecast_df["Actual"],
    label="Actual",
    linewidth=3
)

plt.plot(
    forecast_df["Forecast"],
    label="Forecast",
    linewidth=2
)

plt.legend()

plt.title("Actual vs SARIMA Forecast")

plt.show()

forecast_df["Error"] = (

    forecast_df["Actual"]

    -

    forecast_df["Forecast"]

)

forecast_df.head()

plt.figure(figsize=(10,5))

sns.histplot(
    forecast_df["Error"],
    bins=30,
    kde=True
)

plt.title("Forecast Error Distribution")

plt.show()

metrics = pd.DataFrame({

    "Model":["SARIMA"],

    "MAE":[mae],

    "RMSE":[rmse],

    "MAPE":[mape],

    "R2":[r2],

    "AIC":[best_aic]

})

metrics

forecast_df.to_csv(
    "sarima_forecast.csv",
    index=True
)

metrics.to_csv(
    "sarima_metrics.csv",
    index=False
)

print("Forecast saved successfully.")
print("Metrics saved successfully.")

forecast_df.head(20)



"""# **# Part 4 – SARIMAX Model with Temperature Features**

Install Weather Library
"""

!pip -q install openmeteo-requests requests-cache retry-requests

import pandas as pd
import numpy as np
import requests

from statsmodels.tsa.statespace.sarimax import SARIMAX

"""Download Berlin Temperature"""

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    "?latitude=52.52"
    "&longitude=13.41"
    "&start_date=2015-01-01"
    "&end_date=2020-10-31"
    "&daily=temperature_2m_mean"
    "&timezone=Europe/Berlin"
)

weather = requests.get(url).json()

weather.keys()

temperature = pd.DataFrame({

    "date": weather["daily"]["time"],

    "temp_mean": weather["daily"]["temperature_2m_mean"]

})

temperature.head()

temperature["date"] = pd.to_datetime(
    temperature["date"]
)

temperature.head()

temperature = temperature.set_index("date")

temperature.head()

weekly_temp = temperature.resample("W").mean()

weekly_temp.head()

weekly_temp["HDD"] = np.maximum(
    18 - weekly_temp["temp_mean"],
    0
)

weekly_temp.head()

weekly_temp["CDD"] = np.maximum(
    weekly_temp["temp_mean"] - 18,
    0
)

weekly_temp.head()



"""Plot Temperature"""

plt.figure(figsize=(16,5))

plt.plot(
    weekly_temp.index,
    weekly_temp["temp_mean"],
    color="green"
)

plt.title("Weekly Berlin Temperature")

plt.show()

# Remove timezone from electricity data
weekly.index = weekly.index.tz_localize(None)

# Remove timezone from train/test if needed
train.index = train.index.tz_localize(None)
test.index = test.index.tz_localize(None)

print(weekly.index)

"""Merge Electricity + Temperature"""

sarimax_data = weekly.join(
    weekly_temp,
    how="inner"
)

sarimax_data.head()

print(sarimax_data.isna().sum())

train_exog = sarimax_data.iloc[:-104]

test_exog = sarimax_data.iloc[-104:]

X_train = train_exog[

    [

        "temp_mean",

        "HDD",

        "CDD"

    ]

]

X_test = test_exog[

    [

        "temp_mean",

        "HDD",

        "CDD"

    ]

]

y_train = train_exog["load"]

y_test = test_exog["load"]

sarimax = SARIMAX(

    y_train,

    exog=X_train,

    order=(1,1,1),

    seasonal_order=(1,1,1,52),

    enforce_stationarity=True,

    enforce_invertibility=True

)

sarimax_fit = sarimax.fit(
    disp=False
)

print(sarimax_fit.summary())

forecast = sarimax_fit.get_forecast(

    steps=len(test_exog),

    exog=X_test

)

forecast_mean = forecast.predicted_mean

forecast_ci = forecast.conf_int()

plt.figure(figsize=(18,6))

plt.plot(
    y_train.index,
    y_train,
    label="Training"
)

plt.plot(
    y_test.index,
    y_test,
    label="Actual"
)

plt.plot(
    forecast_mean.index,
    forecast_mean,
    label="SARIMAX"
)

plt.fill_between(
    forecast_ci.index,
    forecast_ci.iloc[:,0],
    forecast_ci.iloc[:,1],
    alpha=0.30
)

plt.legend()

plt.title("SARIMAX Forecast")

plt.show()

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        forecast_mean
    )
)

mae = mean_absolute_error(
    y_test,
    forecast_mean
)

mape = np.mean(
    np.abs(
        (y_test-forecast_mean)
        /
        y_test
    )
)*100

print("RMSE :",round(rmse,2))
print("MAE :",round(mae,2))
print("MAPE :",round(mape,2))

from sklearn.metrics import r2_score

sarimax_r2 = r2_score(
    np.asarray(y_test).flatten(),
    np.asarray(forecast_mean).flatten()
)

sarimax_metrics = pd.DataFrame({

    "Model":["SARIMAX"],

    "MAE":[mae],

    "RMSE":[rmse],

    "MAPE":[mape],

    "R2":[sarimax_r2]

})

sarimax_metrics

"""**Compare SARIMA vs SARIMAX**"""

comparison = pd.DataFrame({

    "Model":[

        "SARIMA",

        "SARIMAX"

    ],

    "RMSE":[

        metrics["RMSE"].iloc[0],

        rmse

    ]

})

comparison

"""Save Results"""

comparison.to_csv(
    "sarima_vs_sarimax.csv",
    index=False
)

print("Comparison saved successfully.")



"""#Part 5 – Feature-Based Models

Import Libraries
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np
import pandas as pd



"""Create Feature Dataset"""

ml_data = sarimax_data.copy()

ml_data.head()

"""Create Time-Series Features"""

# Lag features
ml_data["lag_1"] = ml_data["load"].shift(1)
ml_data["lag_2"] = ml_data["load"].shift(2)
ml_data["lag_3"] = ml_data["load"].shift(3)
ml_data["lag_4"] = ml_data["load"].shift(4)

# Rolling statistics
ml_data["rolling_mean_4"] = ml_data["load"].rolling(4).mean()
ml_data["rolling_std_4"] = ml_data["load"].rolling(4).std()

# Calendar features
ml_data["month"] = ml_data.index.month
ml_data["week"] = ml_data.index.isocalendar().week.astype(int)
ml_data["year"] = ml_data.index.year

ml_data.head()



"""Remove Missing Values"""

ml_data = ml_data.dropna()

print(ml_data.shape)

"""Feature List"""

features = [

    "temp_mean",

    "HDD",

    "CDD",

    "lag_1",

    "lag_2",

    "lag_3",

    "lag_4",

    "rolling_mean_4",

    "rolling_std_4",

    "month",

    "week",

    "year"

]

target = "load"

"""Train/Test Split"""

train_ml = ml_data.iloc[:-104]

test_ml = ml_data.iloc[-104:]

X_train = train_ml[features]
X_test = test_ml[features]

y_train = train_ml[target]
y_test = test_ml[target]

print(X_train.shape)
print(X_test.shape)

"""Train Random Forest"""

rf = RandomForestRegressor(

    n_estimators=300,

    max_depth=12,

    random_state=42

)

rf.fit(
    X_train,
    y_train
)

rf_pred = rf.predict(
    X_test
)



"""Train Gradient Boosting"""

gb = GradientBoostingRegressor(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=3,

    random_state=42

)

gb.fit(
    X_train,
    y_train
)

gb_pred = gb.predict(
    X_test
)



"""Evaluation Function"""

def evaluate_model(name, actual, predicted):

    mae = mean_absolute_error(actual, predicted)

    rmse = np.sqrt(
        mean_squared_error(actual, predicted)
    )

    mape = np.mean(
        np.abs((actual-predicted)/actual)
    )*100

    r2 = r2_score(actual, predicted)

    return [

        name,

        mae,

        rmse,

        mape,

        r2

    ]



"""Evaluate Models"""

rf_results = evaluate_model(

    "Random Forest",

    y_test,

    rf_pred

)

gb_results = evaluate_model(

    "Gradient Boosting",

    y_test,

    gb_pred

)

comparison_ml = pd.DataFrame(

    [

        rf_results,

        gb_results

    ],

    columns=[

        "Model",

        "MAE",

        "RMSE",

        "MAPE",

        "R2"

    ]

)

comparison_ml

ml_metrics = comparison_ml.copy()

ml_metrics.rename(
    columns={
        "R2":"R2"
    },
    inplace=True
)

ml_metrics



"""Plot Predictions"""

plt.figure(figsize=(18,6))

plt.plot(

    y_test.index,

    y_test,

    label="Actual",

    linewidth=3

)

plt.plot(

    y_test.index,

    rf_pred,

    label="Random Forest"

)

plt.plot(

    y_test.index,

    gb_pred,

    label="Gradient Boosting"

)

plt.legend()

plt.title("Machine Learning Forecasts")

plt.show()



"""Feature Importance (Random Forest)"""

importance = pd.DataFrame({

    "Feature":features,

    "Importance":rf.feature_importances_

})

importance = importance.sort_values(

    by="Importance",

    ascending=False

)

importance

"""Feature Importance Plot"""

plt.figure(figsize=(10,6))

plt.barh(

    importance["Feature"],

    importance["Importance"]

)

plt.title("Random Forest Feature Importance")

plt.gca().invert_yaxis()

plt.show()



"""Save Predictions"""

prediction_df = pd.DataFrame({

    "Actual":y_test,

    "Random_Forest":rf_pred,

    "Gradient_Boosting":gb_pred

})

prediction_df.to_csv(

    "feature_model_predictions.csv"

)

prediction_df.head()



"""Save Metrics"""

comparison_ml.to_csv(

    "feature_model_metrics.csv",

    index=False

)

comparison_ml



"""Compare All Models"""

all_models = pd.DataFrame({

    "Model":[

        "Seasonal Naive",

        "SARIMA",

        "SARIMAX",

        "Random Forest",

        "Gradient Boosting"

    ],

    "RMSE":[

        seasonal_rmse,

        rmse,

        rmse,

        comparison_ml.loc[
            comparison_ml.Model=="Random Forest",
            "RMSE"
        ].values[0],

        comparison_ml.loc[
            comparison_ml.Model=="Gradient Boosting",
            "RMSE"
        ].values[0]

    ]

})

all_models



"""# Part 6 – LSTM Forecasting"""

!pip -q install tensorflow

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM,
    Dense,
    Dropout
)

from tensorflow.keras.callbacks import EarlyStopping



"""**Using Weekly Load Data**



"""

lstm_data = weekly.copy()

lstm_data = lstm_data[["load"]]

lstm_data.head()



"""**Normalizing The Data**"""

scaler = MinMaxScaler()

scaled = scaler.fit_transform(
    lstm_data
)

scaled.shape

"""Sequence *Length*"""

sequence_length = 12

"""Create Sequences"""

X = []
y = []

for i in range(sequence_length, len(scaled)):

    X.append(
        scaled[i-sequence_length:i]
    )

    y.append(
        scaled[i]
    )

X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

split = len(X)-104

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

print(X_train.shape)
print(X_test.shape)

model = Sequential()

model.add(

    LSTM(

        64,

        return_sequences=True,

        input_shape=(

            X_train.shape[1],

            X_train.shape[2]

        )

    )

)

model.add(
    Dropout(0.2)
)

model.add(

    LSTM(
        32
    )

)

model.add(
    Dropout(0.2)
)

model.add(
    Dense(1)
)

model.summary()

pred = model.predict(X_test)

actual = scaler.inverse_transform(y_test)

pred = scaler.inverse_transform(pred)

"""Compile"""

model.compile(

    optimizer="adam",

    loss="mse",

    metrics=["mae"]

)



"""Early Stopping"""

early_stop = EarlyStopping(

    monitor="val_loss",

    patience=10,

    restore_best_weights=True

)

history = model.fit(

    X_train,

    y_train,

    epochs=100,

    batch_size=16,

    validation_split=0.2,

    callbacks=[early_stop],

    verbose=1

)



"""Training Curve"""

plt.figure(figsize=(12,5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.legend()

plt.title("LSTM Training")

plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate LSTM metrics
lstm_mae = mean_absolute_error(actual.flatten(), pred.flatten())

lstm_rmse = np.sqrt(
    mean_squared_error(actual.flatten(), pred.flatten())
)

lstm_mape = np.mean(
    np.abs((actual.flatten() - pred.flatten()) / actual.flatten())
) * 100

lstm_r2 = r2_score(
    actual.flatten(),
    pred.flatten()
)

print("LSTM Results")
print("--------------------------")
print("MAE :", round(lstm_mae,2))
print("RMSE :", round(lstm_rmse,2))
print("MAPE :", round(lstm_mape,2))
print("R2 :", round(lstm_r2,4))

lstm_metrics = pd.DataFrame({

    "Model":["LSTM"],

    "MAE":[lstm_mae],

    "RMSE":[lstm_rmse],

    "MAPE":[lstm_mape],

    "R2":[lstm_r2]

})

lstm_metrics

"""Prediction"""

pred = model.predict(
    X_test
)

pred.shape

pred = scaler.inverse_transform(pred)

actual = scaler.inverse_transform(y_test)



"""Evaluation"""

mae = mean_absolute_error(
    actual,
    pred
)

rmse = np.sqrt(
    mean_squared_error(
        actual,
        pred
    )
)

mape = np.mean(
    np.abs(
        (actual-pred)
        /
        actual
    )
)*100

r2 = r2_score(
    actual,
    pred
)

print("MAE :",round(mae,2))

print("RMSE :",round(rmse,2))

print("MAPE :",round(mape,2))

print("R2 :",round(r2,4))



"""Save Forecast"""

lstm_forecast = pd.DataFrame({

    "Actual":actual.flatten(),

    "Forecast":pred.flatten()

})

lstm_forecast.to_csv(

    "lstm_forecast.csv",

    index=False

)

lstm_forecast.head()

plt.figure(figsize=(18,6))

plt.plot(
    lstm_forecast["Actual"],
    label="Actual",
    linewidth=2,
    color="blue"
)

plt.plot(
    lstm_forecast["Forecast"],
    label="LSTM Forecast",
    linewidth=2,
    color="red"
)

plt.title("LSTM Forecast vs Actual Electricity Demand", fontsize=16)

plt.xlabel("Test Weeks", fontsize=12)

plt.ylabel("Electricity Demand (MW)", fontsize=12)

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

lstm_metrics = pd.DataFrame({

    "Model":["LSTM"],

    "MAE":[mae],

    "RMSE":[rmse],

    "MAPE":[mape],

    "R2":[r2]

})

lstm_metrics

sarima_rmse = rmse
sarimax_rmse = rmse
lstm_rmse = rmse

"""Save Metrics CSV"""

lstm_metrics.to_csv(

    "lstm_metrics.csv",

    index=False

)

print("Saved Successfully")

"""##Compare All Models"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ==========================
# Final Model Comparison
# ==========================

results = pd.DataFrame({

    "Model":[
        "Mean",
        "Naïve",
        "Seasonal Naïve",
        "Drift",
        "SARIMA",
        "SARIMAX",
        "Random Forest",
        "Gradient Boosting",
        "LSTM"
    ],

    "MAE":[
        3788.833,
        3783.203,
        2318.521,
        4339.891,
        1963.878,
        5248.560,
        1501.451,
        1308.418,
        lstm_mae
    ],

    "RMSE":[
        4397.300,
        4459.109,
        3006.761,
        5117.957,
        2742.068,
        6479.630,
        2091.480,
        1761.025,
        lstm_rmse
    ],

    "MAPE":[
        6.969,
        6.790,
        4.409,
        8.050,
        3.631,
        9.990,
        2.816,
        2.458,
        lstm_mape
    ],

    "R²":[
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        0.606,
        -2.198,
        0.771,
        0.838,
        lstm_r2
    ]

})

results = results.round(3)

print("="*70)
print("GERMAN ELECTRICITY DEMAND FORECASTING")
print("MODEL COMPARISON")
print("="*70)

display(results)

# Save CSV
results.to_csv(
    "Final_Model_Comparison.csv",
    index=False
)

print("\nResults saved as Final_Model_Comparison.csv")

best = all_models.loc[
    all_models["RMSE"].idxmin()
]

print("="*60)
print("BEST MODEL")
print("="*60)

print(best)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.bar(
    all_models["Model"],
    all_models["RMSE"]
)

plt.title("Comparison of Forecasting Models (RMSE)")

plt.xlabel("Models")

plt.ylabel("RMSE")

plt.xticks(rotation=45)

plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

plt.show()

test_exog

sarimax_actual = test_exog["load"]
sarimax_forecast = forecast_mean

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

sarimax_actual = np.asarray(test_exog["load"]).reshape(-1)
sarimax_forecast = np.asarray(forecast_mean).reshape(-1)

sarimax_mae = mean_absolute_error(sarimax_actual, sarimax_forecast)

sarimax_rmse = np.sqrt(
    mean_squared_error(sarimax_actual, sarimax_forecast)
)

sarimax_mape = np.mean(
    np.abs((sarimax_actual - sarimax_forecast) / sarimax_actual)
) * 100

sarimax_r2 = r2_score(
    sarimax_actual,
    sarimax_forecast
)

print("MAE :", round(sarimax_mae,2))
print("RMSE :", round(sarimax_rmse,2))
print("MAPE :", round(sarimax_mape,2))
print("R² :", round(sarimax_r2,4))

